# Generated by Django 6.0.1 on 2026-02-17 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroTXT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centro', models.CharField(max_length=10)),
                ('periodo', models.CharField(max_length=10)),
                ('tipo_examen', models.CharField(max_length=100)),
                ('area_lab', models.CharField(max_length=100)),
                ('servicio', models.CharField(max_length=150)),
                ('dni_profesional', models.CharField(max_length=15)),
                ('profesional', models.CharField(max_length=150)),
                ('dni_paciente', models.CharField(max_length=15)),
                ('paciente', models.CharField(max_length=150)),
                ('sexo', models.CharField(max_length=1)),
                ('cod_examen', models.CharField(max_length=20)),
                ('desc_examen', models.TextField()),
                ('fecha_solicitud', models.DateField(null=True)),
                ('hora_solicitud', models.CharField(max_length=10, null=True)),
                ('tipo_seguro', models.CharField(max_length=100)),
                ('tipo_paciente', models.CharField(max_length=100)),
                ('sede', models.CharField(max_length=100)),
                ('edad_anios', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
