# Generated by Django 6.0.1 on 2026-03-08 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medireport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamenResultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acto_medico', models.CharField(db_index=True, max_length=50)),
                ('examen', models.CharField(blank=True, max_length=50, null=True)),
                ('descexamen', models.CharField(blank=True, max_length=255, null=True)),
                ('arealab', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('servicio', models.CharField(blank=True, max_length=150, null=True)),
                ('dni', models.CharField(blank=True, max_length=20, null=True)),
                ('paciente', models.CharField(blank=True, max_length=255, null=True)),
                ('sexo', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_solicitud', models.DateField(blank=True, null=True)),
                ('fecha_resultado', models.DateField(blank=True, db_index=True, null=True)),
                ('resultado', models.CharField(blank=True, max_length=50, null=True)),
                ('diagnostico', models.CharField(blank=True, max_length=20, null=True)),
                ('des_diagn', models.CharField(blank=True, max_length=255, null=True)),
                ('profesional', models.CharField(blank=True, max_length=255, null=True)),
                ('informe_resultado', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'examen_resultado',
            },
        ),
        migrations.CreateModel(
            name='ExamenSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_actmed', models.CharField(db_index=True, max_length=50)),
                ('cod_examen', models.CharField(blank=True, max_length=50, null=True)),
                ('desc_examen', models.CharField(blank=True, max_length=255, null=True)),
                ('arealab', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('servicio', models.CharField(blank=True, max_length=150, null=True)),
                ('dni_pac', models.CharField(blank=True, max_length=20, null=True)),
                ('paciente', models.CharField(blank=True, max_length=255, null=True)),
                ('sexo', models.CharField(blank=True, max_length=10, null=True)),
                ('fech_solic', models.DateField(blank=True, db_index=True, null=True)),
                ('horsolic', models.CharField(blank=True, max_length=10, null=True)),
                ('tipo_seguro', models.CharField(blank=True, max_length=100, null=True)),
                ('dni_profesional', models.CharField(blank=True, max_length=20, null=True)),
                ('profesional', models.CharField(blank=True, max_length=255, null=True)),
                ('sede', models.CharField(blank=True, max_length=100, null=True)),
                ('annos', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'examen_solicitud',
            },
        ),
    ]
