# Generated by Django 6.0.1 on 2026-06-21 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medireport', '0002_examenresultado_examensolicitud'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteGuardado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('datos', models.JSONField()),
            ],
            options={
                'db_table': 'reporte_guardado',
            },
        ),
    ]
