# Generated by Django 6.0.1 on 2026-06-23 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medireport', '0004_examenunificado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporteguardado',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.AddField(
            model_name='reporteguardado',
            name='autor',
            field=models.ForeignKey(blank=True, help_text='Usuario propietario/creador del reporte', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reporteguardado',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción breve del reporte', null=True),
        ),
        migrations.AddField(
            model_name='reporteguardado',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reporteguardado',
            name='publicado',
            field=models.BooleanField(default=False, help_text='Si es True, otros usuarios pueden ver este reporte'),
        ),
    ]
